server:
  port: 88
spring:
  application:
    name: yyseckill-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://yyseckill-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*),/$\{segment}

        - id: seckill_route
          uri: lb://yyseckill-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/seckill/(?<segment>.*),/$\{segment}